POST https://risva-rachna-rv54.vercel.app/login
Content-Type: application/json

{
    "username" : "ajitesh10",
    "password" : "pass#123"
}




# POST http://localhost:3000/mysql
# Content-Type: application/json

# {
#     "companyId" : "(drop table x)"
# }
